### ISSUE TITLE
[feedback] [public commentary] How does this benefit USERS?

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [WICG/idle-detection#44]
Lots of reasons why/how this could benefit developers -- especially developers who participate in the surveillance-economy -- but zero explanation about how this could benefit regular users.

As a user, I certainly do not want my hardware (keyboard, mouse), or any other out-of-context status reported to or detectable by a some bit of injected js.

If this is to be established as a standard, the question of how it benefits users and not just developers and site hosts, must be answered.

1. What risks of abuse does this create? (I can think of dozens. Can you?)
2. How are those risks mitigated in code?
3. What benefit is provide to a site or web-application's _users_?
4. What alternative means of providing [benefit] _already_ exist?
5. How does this improve upon prior art?
6. In what ways is this inferior to prior art?

**Comment by tomayac** [comment]
Additional more Web (instead of browser) developer-focused documentation of the use cases: https://web.dev/idle-detection/#use-cases.
