### ISSUE TITLE
Double check permissions integration

### ISSUE THREAD

**Issue by kenchris** [WICG/idle-detection#45]
This doesn't look right to me @marcoscaceres

![image](https://user-images.githubusercontent.com/1101339/155505576-5edbdc1d-a1a4-43f4-90b6-cbb73af9b0d2.png)

**Comment by marcoscaceres** [comment]
Thanks! Will take a look ASAP.

**Comment by reillyeon** [comment]
Ah yes, just checking permission state doesn't require running "in parallel" and since we aren't running "in parallel" there's no need to queue a task. Oops.

**Comment by marcoscaceres** [comment]
yes, exactly 🙂 @reillyeon, you want me to send a PR? Otherwise, happy to review.

**Comment by reillyeon** [comment]
A PR would be appreciated.
